dist: trusty
sudo: false
language: java

addons:
  postgresql: "9.6"

before_install:
  - export PAGER=cat
  # create Flamingo database
  - psql --version
  - psql -U postgres -d postgres -c 'SELECT Version();'
  - psql -U postgres -a -c "CREATE ROLE flamingo4 LOGIN PASSWORD 'flamingo4' SUPERUSER CREATEDB;"
  - psql -U postgres -a -c 'create database flamingo4;'
  - psql -U postgres -a -c 'ALTER DATABASE flamingo4 OWNER TO flamingo4;'

install:
  # install without testing
  - travis_wait 30 mvn --settings .travis/settings.xml -Ptravis-ci-prebuild install -U -DskipTests -Dtest.skip.integrationtests=true -B -V -fae -T4.2C

script:
  - ulimit -a
  - free -m
  # execute unit tests
  - mvn -e clean test -B
  # run integration tests on all modules except viewer-admin
  - mvn -e clean verify -B -Ptravis-ci -pl '!viewer-admin'
  # run integration tests on viewer-admin module only
  - mvn -e clean verify -B -Ptravis-ci -pl 'viewer-admin'
  # run code coverage
  - mvn cobertura:cobertura -Ptravis-ci
  # on oracle java 8 run a javadoc build to check for errors
  - if [ "$TRAVIS_JDK_VERSION" == oraclejdk8 ]; then
         mvn javadoc:javadoc;
    fi
  # on oracle java 8 run a test-javadoc build to check for errors
  - if [ "$TRAVIS_JDK_VERSION" == oraclejdk8 ]; then
         mvn javadoc:test-javadoc;
    fi

after_success:
  - if [ "$TRAVIS_JDK_VERSION" == oraclejdk8 ]; then
         bash <(curl -s https://codecov.io/bash)
    fi
  
jdk:
  - oraclejdk8
  - openjdk8

os:
  - linux

matrix:
  fast_finish: true

cache:
  directories:
  - $HOME/.m2
