version: '{build}-({branch})'

skip_tags: true
clone_folder: C:\projects\flamingo
clone_depth: 20

environment:
  fast_finish: true

  matrix:
  - JDK: JDK7
    JAVA_HOME: C:\Program Files\Java\jdk1.7.0
  - JDK: JDK8
    JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - cmd: echo %PATH%
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-http-proxy.ps1'))
  - ps: .\.appveyor\set-maven-proxy.ps1
  - mvn install -U -DskipTests -pl "web-commons,viewer-commons,viewer-config-persistence" -B -V -fae -q
  
cache:
  - C:\Users\appveyor\.m2\repository -> pom.xml

build: off

test_script:
  - mvn -e test -B
