version: '{build}-({branch})'

skip_tags: true
skip_commits:
  files:
    - 'tailormap-components/**'
    
clone_folder: C:\projects\tailormap
clone_depth: 20
image: Visual Studio 2019

init:
  - cmd: net start %SQL%

environment:
  fast_finish: true

  matrix:
    - JDK: JDK11
      JAVA_HOME: C:\Program Files\Java\jdk11
      SQL: MSSQL$SQL2019
      INSTANCENAME: SQL2019

install:
  - choco install codecov
  - cmd: echo %PATH%
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-http-proxy.ps1'))
  - ps: .\.appveyor\set-maven-proxy.ps1
  - ps: Invoke-WebRequest http://cert.pkioverheid.nl/EVRootCA.cer -OutFile .\EVRootCA.cer
  # load pki-overheid EV root certificate on java 11
  - cmd: if "%JDK%"=="JDK11" keytool -importcert -file .\EVRootCA.cer -alias EV -keystore "%JAVA_HOME%\lib\security\cacerts" -storepass changeit -v -noprompt -trustcacerts
  - mvn install -U -DskipTests -Dtest.skip.integrationtests=true -B -V -fae
  
before_test:
  - sqlcmd -S (local)\%INSTANCENAME% -U sa -P Password12! -Q "CREATE DATABASE flamingo4" -d "master"

cache:
  - C:\Users\appveyor\.m2\repository -> pom.xml

build: off

test_script:
  - mvn -e clean test -B
  - mvn -e verify -B -Pappveyor
  - codecov -v -f target/site/jacoco-it/jacoco.xml target/site/jacoco/jacoco.xml
