name: Ubuntu Maven build

on: [push, pull_request, workflow_dispatch]
  paths:
      - '**.java'
      - '**.xml'
      - '**.js'
      - '**.yaml'
#on:
#  push:
#    branches:
#    - master
#    - v5.8.x
#    - v5.6.x
#    - v5.4.x
#  pull_request:
#    branches:
#    - master
#    - v5.4.x
#    - v5.6.x
#    - v5.8.x
#  workflow_dispatch:
#    branches: []
 
jobs:
  build:
    name: Ubuntu Java ${{ matrix.java }}
    runs-on: [ubuntu-20.04]
    strategy:
      matrix:
        java: [1.8, 11]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: setup database
        run: |
          sudo systemctl start postgresql.service
          psql --version
          sudo -u postgres psql -d postgres -c 'SELECT Version();' || true
          sudo -u postgres psql -a -c "CREATE ROLE flamingo4 LOGIN PASSWORD 'flamingo4' SUPERUSER CREATEDB;"
          sudo -u postgres psql -a -c 'CREATE DATABASE flamingo4;'
          sudo -u postgres psql -a -c 'ALTER DATABASE flamingo4 OWNER TO flamingo4;'
      - name: setup geoserver
        run: |
          docker-compose -f viewer-commons/docker/geoserver/docker-compose.yml up -d
          sudo npm install -g wait-on
          wait-on -t 120000 http-get://localhost:8600/geoserver && echo "docker geoserver is up" || true
      - name: Priming build with Maven
        run: mvn install -DskipTests -Dtest.skip.integrationtests=true -B -V -fae
      - name: Test with Maven
        run: |
          mvn -e clean test -B
          mvn -e verify -B -Pgh-action -pl '!viewer-admin'
          mvn -e verify -B -Pgh-action -pl 'viewer-admin'
      - name: build javadoc
        if: ${{ matrix.java == '1.8' }}
        run: |
          mvn javadoc:javadoc
          mvn javadoc:test-javadoc
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
